// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZMz2T_imST9SP7_P7FOwKZyLXJeXhicY',
    appId: '1:701397058783:web:264b6805674aa5ddd0956a',
    messagingSenderId: '701397058783',
    projectId: 'salfetka-9bb1d',
    authDomain: 'salfetka-9bb1d.firebaseapp.com',
    storageBucket: 'salfetka-9bb1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4e788KHY56iTNFsmzztO7An5NQrtyCI',
    appId: '1:701397058783:android:0047a260c51b84f0d0956a',
    messagingSenderId: '701397058783',
    projectId: 'salfetka-9bb1d',
    storageBucket: 'salfetka-9bb1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlsFf_Iz1CyjSIzxjeqKPoic711HnI54',
    appId: '1:701397058783:ios:2a4b5f5f61c745b0d0956a',
    messagingSenderId: '701397058783',
    projectId: 'salfetka-9bb1d',
    storageBucket: 'salfetka-9bb1d.firebasestorage.app',
    iosBundleId: 'com.zharkynismagulov.salfetka5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzlsFf_Iz1CyjSIzxjeqKPoic711HnI54',
    appId: '1:701397058783:ios:ab017bb314ce5d2fd0956a',
    messagingSenderId: '701397058783',
    projectId: 'salfetka-9bb1d',
    storageBucket: 'salfetka-9bb1d.firebasestorage.app',
    iosBundleId: 'com.example.salfetka5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZMz2T_imST9SP7_P7FOwKZyLXJeXhicY',
    appId: '1:701397058783:web:b9484c0f8efedfc1d0956a',
    messagingSenderId: '701397058783',
    projectId: 'salfetka-9bb1d',
    authDomain: 'salfetka-9bb1d.firebaseapp.com',
    storageBucket: 'salfetka-9bb1d.firebasestorage.app',
  );

}